//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Personajes.CapaDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Personaje
    {
        public int PersonajeID { get; set; }
        public string PersonajeNombre { get; set; }
        public int RazaID { get; set; }
        public int ClaseID { get; set; }
        public string Arma { get; set; }
        public string ArmaNombre { get; set; }
        public int Monedas { get; set; }
        public string Reino { get; set; }
        public string MonturaNombre { get; set; }
        public string ColorArmadura { get; set; }
        public string Lenguaje { get; set; }
    }
}
